FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY requirements.txt .
# Add AI specific dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install transformers speechbrain

COPY app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
